[build]
  base = "src/client"
  publish = "build"
  command = "npm run build"

[dev]
  command = "npm run start"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-react-refresh"

[[plugins]]
  package = "@netlify/plugin-graphql"
