[build]
  base = "src/client"  # Ruta base para los comandos de construcción
  command = "npm run build --prefix src/client"  # Comando de construcción
  publish = "build"  # Directorio de publicación relativo a la ruta base
  functions = "src/server/lambda"  # Directorio de funciones relativo a la ruta base
